<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
شکلات‌های خوب‌تر
</font>
</h1>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
فرض کنید که بعد از میل کردن چند شکلات معمولی (غیر دارک) متوجه شده‌ایم که بسیاری از آن‌ها هم خوشمزه هستند و اگر بتوانیم موارد با کیفیت‌تر آن‌ها را پیدا کنیم احتمالاً فروش خوبی خواهند داشت. پس در گام آخر از پروژه می‌خواهیم شرکت‌هایی که شکلات‌های باکیفیت‌تری را تولید می‌کنند شناسایی کرده و شکلات‌های ‌‌آن‌ها را جدا کنیم.
</font>
</p>


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در گام پیشین قیمت شکلات‌ها را تخمین زده و دیتافریم نهایی را در فایلی به نام <code>chocolate_price.csv</code> ذخیره کردید. در ابتدا آن فایل را به شکل یک دیتافریم بخوانید.
</font>
</p>


In [ ]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ML/DataMining/گام دوم: فروش شکلات/chocolate_price.csv')
df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
توجه داشته باشید که در این گام تنها با شکلات‌های غیرتلخ کار داریم. پس در ابتدا تنها شکلات‌هایی که درصد کاکائوی آن‌ها کمتر یا مساوی  ۷۰ درصد است را جدا کرده و در دیتافریم <code>df</code> ذخیره کنید.
</font>
</p>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از جداسازی و ساخت دیتافریم، به کمک تابع <code dir=ltr>reset_index()</code> نمایه‌ها را ریست کنید. در این مرحله به آرگومان‌های <code>inplace</code> و <code>drop</code> هم توجه کنید.
</font>
</p>

In [ ]:
df = df[df['Cocoa Percent'] <= 70]
df = df.reset_index(drop=True)
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0
...,...,...,...,...,...,...,...,...,...
995,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru,131250.0
996,Zotter,Congo,2011,65.0,Austria,60.0,Forastero,Congo,97500.0
997,Zotter,Kerala State,2011,65.0,Austria,70.0,Forastero,India,113750.0
998,Zotter,Kerala State,2011,62.0,Austria,65.0,Blend,India,100750.0


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این قسمت به ازای هر شرکت شکلات‌سازی، میانگین امتیاز شکلات‌های آن را برای هر سال محاسبه کرده و همچون جدول زیر در دیتافریم <code>companies</code> ذخیره کنید.

<center>

| | 2006 | ... | 2015 | 2016 | 2017 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| A. Morin | NaN | ... | 63.75 | 75.0 | NaN |
| ... | ... | ... | ... | ... | ...  |
| hexx | NaN | ... | 60.00 | NaN | NaN |
| twenty-four blackbirds | NaN | ... | NaN | NaN | NaN |

</center>
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از استفاده از دستور <code>groupby</code> و محاسبه‌ی میانگین از دستور <code>unstack</code> استفاده کنید.
</font>
</p>

In [ ]:
# Group by 'Company' and 'Review Date' and calculate the mean of 'Rating'
grouped = df.groupby(['Company', 'Review Date'])['Rating'].mean()

# Reshape a Pandas DataFrame Using unstack() method
companies = grouped.unstack()
companies

Review Date,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Company,,,,,,,,,,,,
A. Morin,NaN,NaN,NaN,NaN,NaN,NaN,72.500000,66.363636,70.0,63.75,75.0,NaN
AMMA,NaN,NaN,NaN,NaN,77.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Acalli,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.00,NaN,NaN
Adi,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,NaN
Aequare (Gianduja),NaN,NaN,NaN,57.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
Zokoko,NaN,NaN,NaN,NaN,NaN,70.0,NaN,NaN,NaN,NaN,65.0,NaN
Zotter,NaN,NaN,NaN,NaN,60.0,67.5,69.285714,NaN,NaN,NaN,NaN,NaN
hello cocoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.00,NaN,NaN


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
خطوط زیر برای استانداردسازی شکل جدول اعمال می‌شوند. این خطوط را تغییر نداده و تنها سلول زیر را اجرا کنید.
</font>
</p>

In [ ]:
companies.columns.name = None
companies.index.name = None

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
برای پیدا کردن بهترین شرکت‌ها می‌خواهیم تنها امتیاز سال‌های ۲۰۱۲ به بعد را در نظر بگیریم (خود سال ۲۰۱۲ را هم در نظر بگیرید).
ابتدا به ازای هر کمپانی، میانگین امتیاز سال‌های ۲۰۱۲ به بعد آن را محاسبه کرده و در متغیر <code>mean_ratings</code> ذخیره کنید.
توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>


In [ ]:
mean_ratings = companies[[col for col in companies.columns if col >= 2012]]
mean_ratings =mean_ratings.mean(axis = 1)
mean_ratings

,0
A. Morin,69.522727
AMMA,NaN
Acalli,75.000000
Adi,NaN
Aequare (Gianduja),NaN
...,...
Zokoko,65.000000
Zotter,69.285714
hello cocoa,55.000000
hexx,60.000000


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون به کمک میانگین امتیاز هر کمپانی (<code>mean_ratings</code>)، ۱۰ کمپانی با بهترین امتیاز را پیدا کنید و در متغیر <code>best_ratings</code> ذخیره کنید. توجه داشته باشید که خروجی شما باید یک سری پانداز (<code>pd.Series</code>) باشد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:purple"><b>توجه:</b></span>
در مواردی که امتیاز کمپانی‌ها یکسان باشد، باید کمپانی را براساس ترتیب حروف الفبا انتخاب کنید. به‌عنوان مثال اگر دو کمپانی <code>A</code> و <code>B</code> هر دو میانگین امتیاز <code>75.00</code> داشته باشند، اولویت با شرکت <code>A</code> است.
</font>
</p>

In [ ]:
mean_ratings = mean_ratings.rename("mean_rating")
best_ratings = mean_ratings.reset_index().sort_values(by=['mean_rating','index'], ascending=[False, True]).set_index('index').head(10)
best_ratings

,mean_rating
index,
Patric,80.000000
Tobago Estate (Pralus),80.000000
Willie's Cacao,80.000000
L.A. Burdick (Felchlin),77.500000
Matale,77.500000
Pacari,77.500000
Valrhona,76.666667
Acalli,75.000000
Amedei,75.000000


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
اکنون شکلات‌هایی که کمپانی سازنده‌شان جزو ۱۰ شرکت برتر (<code>best_ratings</code>) است را از دیتافریم <code>df</code> انتخاب کرده و در دیتافریم <code>chocolates_to_sell</code> ذخیره کنید.
</font>
</p>


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی ۱:</b></span>
بعد از انتخاب این شکلات‌ها، به‌کمک دستور <code>reset_index</code> نمایه‌ها را ریست کنید. استفاده از آرگومان <code>drop</code> را نیز فراموش نکنید.

<br>
<span style="color:green"><b>راهنمایی ۲:</b></span>
برای بررسی وجود یک متغیر در یک لیست می‌توانید از تابع <code>isin</code> استفاده کنید.
</font>
</p>

In [ ]:
chocolates_to_sell = df[df['Company'].isin(best_ratings.index)].reset_index(drop=True)
chocolates_to_sell

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Acalli,"Chulucanas, El Platanal",2015,70.0,U.S.A.,75.0,Blend,Peru,131250.0
1,Acalli,"Tumbes, Norandino",2015,70.0,U.S.A.,75.0,Criollo,Peru,131250.0
2,Amedei,"Piura, Blanco de Criollo",2012,70.0,Italy,75.0,Blend,Peru,131250.0
3,Amedei,Porcelana,2007,70.0,Italy,80.0,Criollo (Porcelana),Venezuela,140000.0
4,Amedei,Chuao,2007,70.0,Italy,100.0,Trinitario,Venezuela,175000.0
5,Amedei,Ecuador,2007,70.0,Italy,60.0,Trinitario,Ecuador,105000.0
6,Amedei,Jamaica,2007,70.0,Italy,60.0,Trinitario,Jamaica,105000.0
7,Amedei,Grenada,2007,70.0,Italy,70.0,Trinitario,Grenada,122500.0
8,Amedei,Venezuela,2007,70.0,Italy,75.0,Trinitario (85% Criollo),Venezuela,131250.0
9,Amedei,Madagascar,2007,70.0,Italy,80.0,Trinitario (85% Criollo),Madagascar,140000.0


In [ ]:
chocolates_to_sell['Company'].value_counts()

,count
Company,
Valrhona,17
Amedei,12
Pacari,10
Patric,5
L.A. Burdick (Felchlin),4
Willie's Cacao,3
Askinosie,3
Acalli,2
Matale,2


<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت پنجم
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در نهایت مجموع قیمت این شکلات‌ها (<code>chocolates_to_sell</code>) را در متغیر <code>priceSum</code> ذخیره کنید تا مجموع دریافتی ما از این شکلات‌ها هم مشخص شود.
</font>
</p>

In [ ]:
priceSum = chocolates_to_sell['price(100g)'].sum()
priceSum

np.float64(7282125.0)

In [ ]:
del chocolates_to_sell['price(100g)']

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zlib
import zipfile

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

df.to_csv('normal_chocolates.csv', index = True)
companies.to_csv('companies.csv', index = True)
chocolates_to_sell.to_csv('chocolates_to_sell.csv', index = True)
mean_ratings.to_csv("mean_ratings.csv", index = True)
best_ratings.to_csv("best_ratings.csv", index = True)

np.savez("answers.npz" ,priceSum = priceSum)
file_names = ["answers.npz", "project1_step3.ipynb", "chocolates_to_sell.csv",
              "companies.csv", "mean_ratings.csv", "best_ratings.csv", "normal_chocolates.csv"]
compress(file_names)

File Paths:
['answers.npz', 'project1_step3.ipynb', 'chocolates_to_sell.csv', 'companies.csv', 'mean_ratings.csv', 'best_ratings.csv', 'normal_chocolates.csv']
